import os
os.system("clear")
os.system("figlet -f big BANNER | lolcat")
a = input("Enter name:-")
b = input("Enter nick name:-")
c = input("Enter pickup line:-")
d = input("Dollar sign:-")
os.system("touch /data/data/com.termux/files/usr/etc/motd")
os.system("rm /data/data/com.termux/files/usr/etc/motd")
file =open("/data/data/com.termux/files/usr/etc/bash.bashrc","w")
file.write('figlet -f big '+ a +' | lolcat\nfiglet -f small '+ b +'\n echo " '+ c +' "\nshopt -s histappend\nshopt -s histverify\nexport HISTCONTROL=ignoreboth\nPROMPT_DIRTRIM=2\nPS1="\[\e[0;32m\]\w\[\e[0m\] \[\e[0;97m\]\ '+ d +' \[\e[0m\] "\nif [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then\n	command_not_found_handle() {\n		/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"\n	}\nfi')
os.system("figlet -f small ADDED")
print("Thanks Your Banner Was Added")
print("Please Exit!")